name: iOS Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false

    - name: Install Ruby dependencies
      run: |
        cd ios
        # Install bundler if not present
        gem install bundler --no-document
        # Install gems from Gemfile if it exists
        if [ -f "Gemfile" ]; then
          bundle config set --local deployment false
          bundle config set --local path vendor/bundle
          bundle install --retry=3
        fi

    - name: Install CocoaPods
      run: |
        cd ios
        # Install CocoaPods if not present
        if ! command -v pod &> /dev/null; then
          echo "Installing CocoaPods..."
          sudo gem install cocoapods --no-document
        fi
        # Install pods
        pod install --repo-update
        
    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS Debug
      run: |
        cd ios
        echo "Building iOS Debug configuration..."
        # List available schemes first
        xcodebuild -workspace CiCdSampleProject.xcworkspace -list
        # Build for simulator
        xcodebuild -workspace CiCdSampleProject.xcworkspace \
                   -scheme CiCdSampleProject \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 14' \
                   clean build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO
                   
    - name: Build iOS Release
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        cd ios
        # Check if Fastlane secrets are available
        if [ -n "${{ secrets.MATCH_PASSWORD }}" ]; then
          echo "Using Fastlane for release build"
          bundle exec fastlane build_release
        else
          echo "Fastlane secrets not configured, using xcodebuild for release build"
          xcodebuild -workspace CiCdSampleProject.xcworkspace \
                     -scheme CiCdSampleProject \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath $PWD/build/CiCdSampleProject.xcarchive \
                     clean archive \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
        fi
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        
    - name: Upload iOS build artifacts
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios/build/
          ios/*.ipa

  deploy-ios:
    name: Deploy to TestFlight
    runs-on: macos-latest
    needs: build-ios
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        working-directory: ios
        
    - name: Download iOS build artifacts
      uses: actions/download-artifact@v5
      with:
        name: ios-build
        path: ios/
        
    - name: Deploy to TestFlight
      run: |
        cd ios
        bundle exec fastlane deploy_testflight
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
